### ISSUE TITLE
extractor.collectChunks does not provide mjs script chunks in getScriptTags fn

### ISSUE THREAD

**Issue by oyo-ravi-yadav** [gregberge/loadable-components#496]
## 🐛 Bug Report

In my webpack i have 2 config for mjs and js scripts
When i try to use my mjs statsfile for extractor.collectChunks it does not provide me the chunks

## To Reproduce

https://github.com/raven619claw/starter-kit/tree/develop
run yarn and then the start cmd 
in file `serverRenderer.js` at line 37 set `deviceSupportsES6` to true 
and at 66 check the `scriptTags` value
For mjs it is empty and works correctly for js builds

## Expected behavior

It should give chunks for mjs build as well

## Link to repl or repo (highly encouraged)

https://github.com/raven619claw/starter-kit/tree/develop

## Run `npx envinfo --system --binaries --npmPackages @loadable/component,@loadable/server,@loadable/webpack-plugin,@loadable/babel-plugin --markdown --clipboard`

Paste the results here:

```bash

```

**Comment by oyo-ravi-yadav** [comment]
Please advice if this is an issue with my webpack build or something else i am missing here

**Comment by theKashey** [comment]
`loadable` [defines](https://github.com/gregberge/loadable-components/blob/master/packages/server/src/ChunkExtractor.js#L12) only `.js` as a "script", that's why it's not added.

So this is a bug. However, there is also no reason for you to use `.mjs`, it was a temporal hack for `nodejs` and dont have to be used nowadays nor for that `nodejs`, nor for the `browser`. Especially for `webpack`, especially as a compilation target.
