### ISSUE TITLE
Why a separate @loadable/webpack-plugin?

### ISSUE THREAD

**Issue by tstirrat15** [gregberge/loadable-components#508]
## 💬 Questions and Help

Looking at the source for both, [@loadable/webpack-plugin](https://github.com/gregberge/loadable-components/tree/master/packages/webpack-plugin) looks a whole lot like [webpack-stats-plugin](https://github.com/FormidableLabs/webpack-stats-plugin).

One difference between them is that `webpack-stats-plugin` is compatible with the [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer#usage-as-a-cli-utility) CLI, and `@loadable/webpack-plugin` is not. This is down to [`@loadable/webpack-plugin` explicitly excluding parts of the stats file](https://github.com/gregberge/loadable-components/blob/master/packages/webpack-plugin/src/index.js#L19-L27), which the [stats plugin does not](https://github.com/FormidableLabs/webpack-stats-plugin/blob/master/lib/stats-writer-plugin.js#L65-L68).

My questions:

1. Why are those fields excluded at all?
1. If they don't need to be excluded (i.e. adding an option that's passed through to the stats emitter), is there a meaningful difference between this package and `webpack-stats-plugin`?
1. If there isn't, why does this repo reimplement `webpack-stats-plugin` rather than using/peerdepping it?

**Comment by theKashey** [comment]
1. Because loadable don't need them.
2. Yes. They don't need to be excluded
3. To hide the implementation details. And to be concrete - because you don't have to use `webpack-stats-plugin` - it's a ONE call to webpack internals, and you might ask webpack to generate `stat` file for you (`--stats`)

Anyway, the problem with `stats` was "fixed" and documented - https://github.com/gregberge/loadable-components/pull/487
