### ISSUE TITLE
Prevent preloading a chunk even if it is used on the server

### ISSUE THREAD

**Issue by xtroncode** [gregberge/loadable-components#578]
## 💬 Questions and Help

I have a ssr enabled site and am trying to use progressive hydration on the client side, but since the component is rendered on the server side, `ChunkExtractor` reports the chunk in `getScriptTags` and `getLinkTags` . I want to load the corresponding chunks for a component only when it is about to get hydrated (i.e. enter the viewport) . Is there a way where I can tell loadable to exclude a chunk from being reported as being used ?

**Comment by jee** [comment]
This may not be exactly what you're looking for, since I'm guessing you want your chunks rendered on the server for SEO reasons and only partially hydrating the client for performance, but... If you're not worried about SEO, I've tried `react-loadable-visibility` and it loads chunks when they enter the viewport. The library acts as a wrapper over `loadable-components` and utilizes intersection observer.

While a super interesting solution and works as it's documented, I ended up not using it because the library seems to require that you set the `loadable-component` chunk to `ssr: false` and I need the complete static markup from the server for SEO reasons.

Hopefully the author or others can help provide insightful comments on this thread.

**Comment by markwoodward23** [comment]
@xtroncode I've actually done actually that in a company project - I'll see if I can extract it into something more open. Essentially we use loadable for the common things like vendor bundles etc, then anything which is dynamic we use a standard dynamic import, or a require when we're on the server. That generates the dynamic bundles with webpack, requires the module as normal when SSR, and you can lazy hydrate those bundles in on intersection on the client. SEO + performance wins all round. 

Will link to something in the next few days, remind me if not.

**Comment by theKashey** [comment]
You can wrap locations you don't want on the Client with another `ChunkExtractor`, hiding everything behind it form the "application".

**Comment by theneekz** [comment]
> Will link to something in the next few days, remind me if not.

I'd still be curious to see this implementation if you have it @markwoodward23
