### ISSUE TITLE
Dynamic, dynamic imports can't be caught when an error occurs

### ISSUE THREAD

**Issue by madou** [gregberge/loadable-components#609]
## 🐛 Bug Report

When using dynamic dynamic imports I'm unable to catch the promise if the import fails to be found.

## To Reproduce

Run this code in Gatsby using the `gatsby-plugin-loadable-components-ssr` plugin:

```
const LazyIcon = loadable(({ glyph }) => {
  return import(
    /* webpackChunkName: "@atlaskit/icon/glyph/[request]" */ `@atlaskit/icon/glyph/${glyph}`
  ).catch(() => ({
    default: QuestionCircleIcon,
  }));
});

<LazyIcon glpyh="I dont exist" />
```

## Expected behavior

Expected the promise to succeed and to return `QuestionCircleIcon` instead. That didn't happen though - an error was uncaught!

This breaks gatsby SSR build.

cc @theKashey raised for you 🙏

**Comment by theKashey** [comment]
Hey! During babel transformation only `import` (rewritten in `require`) is kept, that's why catch is not working.
There is PR from @hedgepigdaniel with the "fix" for this - https://github.com/gregberge/loadable-components/pull/511/files#diff-ca523cfb451b3ca9f95fbf515dfd416aR122

While we were thinking how to handle named imports or delays - we never thought about fallback behavior for full dynamic import.

**Comment by theKashey** [comment]
Hey @madou - your problem should be fixed by now. Just update and use new `resolveComponent` option.
However, according to #621 full dynamic imports are not working with Gatsby static build.

**Comment by madou** [comment]
will close this and if it comes up again will re-open.

**Comment by theKashey** [comment]
Should be already fine 🤞. It would be great to verify.
