### ISSUE TITLE
Destructure library

### ISSUE THREAD

**Issue by developdeez** [gregberge/loadable-components#711]
Havent seen this in any example but it would be nice if we could destructure libraries loaded. I tried this using below and it failed.
const {registerPlugin} = loadable.lib(() => import('react-filepond'));

**Comment by theKashey** [comment]
Yes, it would not work that way due to many reasons. For example `loadable.lib` is not _loading_ anything until called, so it might not know that `registerPlugin` exists and cannot create an entity with such name.

Technically doable via proxies, but it can be implemented on a side and does not require any extra support from a loadable.

Please look at `names imports` (option.resolveComponent) support for https://loadable-components.com/docs/api-loadable-component/#loadablelib
