### ISSUE TITLE
Change the extractor.getLinkTags and getScriptTags to have options to speed up FCP for PageSpeed

### ISSUE THREAD

**Issue by justin808** [gregberge/loadable-components#720]
## 🚀 Feature Proposal

Numerous web sources suggest using defer and not async for the scripts.

We have found that by only using the first link tag, we get a considerably better (50% smaller) FCP, on pages like 110grill.com. This affects PageSpeed scores.

```js
 const linkTags = extractor.getLinkTags().split('\n')[0];
```

The other scripts get loaded as needed.

Many articles recommend using defer rather than async. 
You can see some articles here: https://www.google.com/search?q=async+scripts+slowing+fcp

It seems that async scripts can pause rendering while the script is evaluated, which increases both FCP and LCP times. 

Using defer instead of async would ensure that scripts are only evaluated after the document is painted. However, we probably don't want to defer code splitting bundles.

Maybe the "link data-chunk" is good enough for the async bundles?

Maybe even the first bundle should be using defer?

![image](https://user-images.githubusercontent.com/1118459/110851576-508a3d00-8255-11eb-98e0-55d2f371afad.png)

## Motivation

**Better page PageSpeed scores!**

## Example

See page source at https://www.110grill.com/

## Pitch

Faster PageSpeed scores!

**Comment by rtymchyk** [comment]
Improving FCP can just increase the gap until the content is interactive, which means worse TTI (time to interactive scores). 

Since TTI is weighed higher than FCP, it's actually sometimes better to "delay" the paint, and so I think defaulting to `defer` vs `async` is not a decision that can be made globally for all apps. It's also worth noting that Next.JS uses `async`. 

Correct me if I'm wrong, but you should be able to provide `{ async: false, defer: true }` to your `getScriptTags` call, if it works better for your app.
