### ISSUE TITLE
How to load default export of a module?

### ISSUE THREAD

**Issue by joshuaquek** [gregberge/loadable-components#747]
How can I use `loadable` with a regular and default export together?

Example: 

```javascript
import Select, { components } from "react-select";
```

If I were to load `Select` and `components` then would it be:
```javascript
const { default: Select,  components } = loadable(() => import('react-select'))
```

Would this be correct?

**Comment by theKashey** [comment]
`One call to "loadable"` == `One component loaded`

- in order to load non default component refer to https://loadable-components.com/docs/api-loadable-component/#optionsresolvecomponent
- in order to load everything some module exposes refer to https://loadable-components.com/docs/library-splitting/
