### ISSUE TITLE
loadable-components for React 18

### ISSUE THREAD

**Issue by rake7h** [gregberge/loadable-components#787]
## 💬 Questions and Helps

We have just migrated one of our old code-base to lodable-components from react-loadable. And it’s working as expected, we are able to do code-splitting per component/routes and even started lazy loading some of the large internal npm module thought lodable-components.

Coming back to my question:

Since, React 18 coming with native support for suspense and react.lazy for SSR, I believe webpack will create the chunk for every lazy import by default and load it as needed on client.

https://github.com/reactwg/react-18/discussions/37

so, do we still need loadable-components for apps running on React 18?

**Comment by theKashey** [comment]
That is a good question, and in short - yes. You will always need some _sugar_ around code-splitting it in order to get the best possible results, however it will be __not required__ to the actual work.

You can think about loadable components as an orchestration layer rather codesplitting itself, and some bits and pieces have to be changed in order to properly support Selective and Progressive Hydration.
