### ISSUE TITLE
Not working with latest @loadable/server & @loadable/babel-plugin `v5.16.0` version

### ISSUE THREAD

**Issue by denchiklut** [gregberge/loadable-components#971]
## 🐛 Bug Report

After updating `@loadable/server` and `@loadable/babel-plugin` to version `v5.16.0` started having an error:
`loadable: SSR requires '@loadable/babel-plugin', please install it`

## To Reproduce
Install latest  `"@loadable/server"` and `"@loadable/babel-plugin"` version `"5.16.0"`
Run the app
You will see the message: `loadable: SSR requires '@loadable/babel-plugin', please install it`

## Expected behavior

It should work the same way it worked with previous versions

## Link to repl or repo (highly encouraged)
https://github.com/denchiklut/ssr-boilerplate/pull/11
- switch to the `feat/update` branch:
- yarn install
- yarn dev (u will see an error "loadable: SSR requires `@loadable/babel-plugin`, please install it")

To see working version:
- switch to the `main` branch
- yarn install
- yarn dev (this time everything will work)

```bash
## System:
 - OS: macOS 13.4.1
 - CPU: (8) arm64 Apple M1 Pro
 - Memory: 63.30 MB / 32.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.0/bin/yarn
 - npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
## npmPackages:
 - @loadable/babel-plugin: 5.16.0 => 5.16.0 
 - @loadable/component: ^5.15.3 => 5.15.3 
 - @loadable/server: 5.16.0 => 5.16.0 
 - @loadable/webpack-plugin: ^5.15.2 => 5.15.2 

```

**Comment by denchiklut** [comment]
@theKashey small update I think the issue is actually only with `@loadable/babel-plugin`.

**Comment by theKashey** [comment]
Thank you for the insight, that would greatly simply the fix process. @denchiklut +++

**Comment by theKashey** [comment]
Root cause - broken "loadable" detection

In your code you just import your stuff as `loadable`, and that's it - https://github.com/denchiklut/ssr-boilerplate/blob/414ff83dc991d59e75db92a031f55b279ee19c15/src/client/components/%40shared/app/routes/index.tsx#L7
"Signatures" broken this moment requiring an explicit configuration, which you should want to implement (😉)

In any case, no breaking changes should occur even for not very widely used functionality and the behaviour has been corrected. 
Currently it's too late to perform release, I'll do it tomorrow morning (and time zones are hard)

**Comment by theKashey** [comment]
`@loadable/babel-plugin@5.16.1` should fix the problem
