### ISSUE TITLE
error  in ./node_modules/@loadable/component/dist/loadable.esm.mjs

### ISSUE THREAD

**Issue by ZhangDubhe** [gregberge/loadable-components#990]
## 🐛 Bug Report
`Can't import the named export 'isValidElementType' from non EcmaScript module (only default export is available)`

## version
5.16.2

**Comment by yofine** [comment]
same problem

webpack 4

**Comment by theKashey** [comment]
This is related to https://github.com/gregberge/loadable-components/pull/989, reason unknown
- this line `https://github.com/gregberge/loadable-components/blob/2210bcf43b0106776a872541f57afca1f3569491/packages/component/src/createLoadable.js#L3C35-L3C35` got transpired in a little different way, ie it became `import { isValidElementType } from 'react-is';` instead of `import * as ReactIs from 'react-is';

Please fallback to version 5.16.1

**Comment by stevegacka** [comment]
I encountered same issue, with Webpack 4. 

Falling back to **5.15.x** of loadable packages resolved for me. NPM reported no 5.16.1 candiate for @loadable/component.

    "@loadable/babel-plugin": "5.15.3",
    "@loadable/component": "5.15.3",
    "@loadable/server": "5.15.3",
    "@loadable/webpack-plugin": "5.15.2",

**Comment by theKashey** [comment]
Correct, [5.15.3](https://www.npmjs.com/package/@loadable/component/v/5.15.3) was the previous version.

**Comment by theKashey** [comment]
[5.16.3](https://github.com/gregberge/loadable-components/commit/8f40762051ba71a75a378af0030e5614d7daf6e3) has been released with the fix.

**Comment by theKashey** [comment]
👋 Can someone confirm that the issue is no longer present so I can close the problem? 🙏

**Comment by stevegacka** [comment]
@theKashey 5.16.3 resolved the issue for me! Thank you 🙏

**Comment by theKashey** [comment]
🚀
